FROM python:3.12-slim AS build
WORKDIR /app

# Wheels + requirements rein
COPY wheels/ wheels/
COPY requirements.txt .

# Offline Installation – funktioniert garantiert
RUN pip install --no-index --find-links=wheels -r requirements.txt


# Final Image
FROM python:3.12-slim
WORKDIR /app

# ➜ WICHTIG: Site-Packages korrekt kopieren
COPY --from=build /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=build /usr/local/bin /usr/local/bin

# Deine Anwendung
COPY ./src ./src

CMD ["python", "src/main.py"]