FROM python:3.12-slim AS build
WORKDIR /app

COPY wheels/ wheels/
COPY requirements.txt .

RUN pip install --no-index --find-links=wheels -r requirements.txt

FROM python:3.12-slim
WORKDIR /app

COPY --from=build /usr/local/lib/python3.12 /usr/local/lib/python3.12
COPY ./src ./src

CMD ["python", "src/main.py"]